const neverExpire = -1;

export const googleCookies = [
  {
    name: "CONSENT",
    value: "PENDING+995",
    domain: ".google.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "OTZ",
    value: "7253775_48_52_123900_48_436380",
    domain: "consent.google.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "SOCS",
    value:
      "CAISNQgEEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjMxMDEwLjAyX3AxGgJlcyACGgYIgJ23qQY",
    domain: ".google.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "NID",
    value:
      "511=KoQJbcFz_8R0rb4OmAb5fHWOWu1WlDHB6kjq9SquOyK-Djtyziz8mslLBPRgwKSALzawIP8u-vhzDUIQT4Wh8vJIwoHe5KC9Z6d-K2PMNeWjmlO7cD371oeZE__Pu5MbU0ZeWx8w35fr8ypdDvo7d2E7CYnh4xjucti-gv7cTXc",
    domain: ".google.com",
    path: "/",
    expires: neverExpire,
    httpOnly: true,
    secure: true,
    sameSite: "None",
  },
  {
    name: "OGPC",
    value: "19039026-1:",
    domain: ".google.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: false,
    sameSite: "Lax",
  },
  {
    name: "OTZ",
    value: "7253775_48_52_123900_48_436380",
    domain: "ogs.google.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "cmplz_consented_services",
    value: "",
    domain: "enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "cmplz_policy_id",
    value: "20",
    domain: "enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "cmplz_marketing",
    value: "allow",
    domain: "enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "cmplz_statistics",
    value: "allow",
    domain: "enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "cmplz_preferences",
    value: "allow",
    domain: "enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "cmplz_functional",
    value: "allow",
    domain: "enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "cmplz_banner-status",
    value: "dismissed",
    domain: "enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: true,
    sameSite: "Lax",
  },
  {
    name: "_ga_7R9CQM0V0N",
    value: "GS1.1.1697531186.1.0.1697531186.0.0.0",
    domain: ".enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: false,
    sameSite: "Lax",
  },
  {
    name: "_ga",
    value: "GA1.2.179155763.1697531186",
    domain: ".enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: false,
    sameSite: "Lax",
  },
  {
    name: "_gid",
    value: "GA1.2.931744258.1697531186",
    domain: ".enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: false,
    sameSite: "Lax",
  },
  {
    name: "_gat_gtag_UA_168765658_1",
    value: "1",
    domain: ".enlavapies.com",
    path: "/",
    expires: neverExpire,
    httpOnly: false,
    secure: false,
    sameSite: "Lax",
  },
];
